while True:
    print("=============================================MENÚ=============================================")
    print("1. Listar consolas de sobremesa o portatiles y después te pregunta si quieres listar los juegos de alguna de ellas.")
    print("2. Contar los juegos de una consola en total y también los que son exclusivos.")
    print("3. Introduce una fecha y te muestra todas las consolas que salieron antes de esa fecha.")
    print("4. Introducir por teclado un juego y te dice de que consola es y el precio de la consola de salida.")
    print("5. Un juego donde eliges una consola y te dice todos los juegos que salieron en ella y tienes 3 intentos para acertar cual fue el mas vendido de la misma.")
    print("6. Salir")
    print("==============================================================================================")
    opc=int(input("Elige una opción: "))